language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'

before_install:
install:
  - npm install
  - npm bootstrap
  - make image-dev
script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make push-dev
after_success:
  - npm run test:prod
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
